version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.6.14-management
    healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:5672"]
        interval: 30s
        timeout: 10s
        retries: 5
    ports:
      - "0.0.0.0:5672:5672"
      - "0.0.0.0:15672:15672"
    networks:
      - node-network
  node:
    depends_on:
      - rabbitmq
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/projects/node
    ports:
      - "3000:3000"
    networks:
      - node-network
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./src/infra/database/init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    user: root
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
networks:
  node-network:
    driver: bridge